project_id = "stmyztkmioobdbxliktn"

[functions.ghl-proxy]
verify_jwt = false

[functions.ghl-sync]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false

[functions.lead-intake]
verify_jwt = false

[functions.ghl-sync-validate]
verify_jwt = false

[functions.wp-token-exchange]
verify_jwt = false

[functions.lead-notify]
verify_jwt = false
